version: '3.8'

services:
  jenkins:
    image: 'ahsand10/jenkins/my-jenkins-image'
    container_name: jenkins-container
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
